---
#
# OSRM 
#
#
- name: download country data file .osm.pbf
  get_url: url=http://download.geofabrik.de/europe/{{data_country_name}}-latest.osm.pbf dest=/home/osrm/{{data_country_name}}-latest.osm.pbf force=no mode=0644
