---
#
# OSRM 
# - installation
# - configuration
#
#
- name: create a user osrm
  user: name={{osrm_role_name}} generate_ssh_key=yes ssh_key_bits=2048

- name: install system packages for osrm compilation
  apt: pkg={{ item }} state=present
  with_items: osrm_ubuntu_pkgs

- name: clone the github repository
  git: >
    repo=https://github.com/DennisOSRM/Project-OSRM.git dest={{osrm_dest_dir}} version={{osrm_version}}

- name: create build directory
  file: dest={{osrm_dest_dir}}/build mode=755 owner=root group=root state=directory

- name: cmake
  shell:
    cmake ..
    chdir={{osrm_dest_dir}}/build

- name: make
  shell:
    make -j {{osrm_make_jobs}}
    chdir={{osrm_dest_dir}}/build

