---
# Creates a new ansible role
# Usage:
#   ansible-playbook ./osrm.yml -i "localhost,"
#
- hosts: local
  connection: local
  become: True
  gather_facts: False
  roles:
    - osrm
    - osrm-data
